### PR TITLE
Allow access to some JVM Build Service Objects

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This allows users of the staging cluster to configure their workspace, and interact with rebuilt artifacts.

fixes PLNSRVCE-893

Users of the appstudio staging cluster that want to use the JVM Build Service (https://github.com/redhat-appstudio/jvm-build-service) need permission to modify these objects to be able to do anything meaningful. 

I am not 100% sure how all this works, so let me know if this is not the right place for this.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
This is the right place. But can you please add an e2e test for this?
See an example of such test: https://github.com/codeready-toolchain/toolchain-e2e/pull/580
Please note, that the e2e tests are in a separate repo: https://github.com/codeready-toolchain/toolchain-e2e
And you have to pair this PR with the e2e test PR buy using the same branch name for both PRs.

The PR check will be failing until you add the test and it passes.

**Review by alexeykazakov — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
I have created the PR at https://github.com/codeready-toolchain/toolchain-e2e/pull/631

**Comment by alexeykazakov** [comment]
/retest

openshift-ci infra issue this time :(

**Pull request merged**
