### PR TITLE
refactor UserSignupController: do not watch SpaceBindings

### PR DESCRIPTION
**Pull request by xcoulon**
Create SpaceBindings with a name based on the Space name and the MasterUserRecord name, so that if the UserSignupController is called just after a SpaceBinding was created but before it was indexed by Etcd (hence, `client.List` with a label matcher would return no result), then creating another SpaceBinding will fail because it would have the same name as the existing one.

see also https://github.com/codeready-toolchain/toolchain-e2e/pull/561

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by rajivnathan — APPROVED** [review]
The changes look good to me but two error messages were changed and I didn't see any unit test changes. Are we missing some coverage?

**Review by ranakan19 — APPROVED** [review]
LGTM

**Pull request merged**
