### PR TITLE
add toolchainclusterresources controller

### PR DESCRIPTION
**Pull request by mfrancisc**
Enable the toolchainclusterresources controller that will create all the required resources for the toolchaincluster CR.
The resources are defined as `embed.FS` type in `deploy.ToolchainClusterTemplateFS` variable

The [add-cluster script](https://github.com/codeready-toolchain/toolchain-cicd/blob/35e64c742cc420f961b9747a429efcb43813916b/scripts/add-cluster.sh#L27-L202) will be cleaned up once this PR and the equivalent one in [member-operator](https://github.com/codeready-toolchain/member-operator/pull/555)  will be merged.

e2e pr: https://github.com/codeready-toolchain/toolchain-e2e/pull/945

Depends on: https://github.com/codeready-toolchain/toolchain-common/pull/385

Jira: https://issues.redhat.com/browse/KUBESAW-24

### CODE REVIEW

**Comment by rsoaresd** [comment]
Hello, @mfrancisc

I noticed that it is failing with EOF:
```
Error:      	Received unexpected error:
        	            	Get "https://host-operator-metrics-service-toolchain-host-04125046.apps.ci-op-rv2x2c9b-1de72.devsandboxci.devcluster.openshift.com/metrics": EOF
        	Test:       	TestAfterMigration
```

The related PR in member-operator is failing with EOF too:

```
Error:      	Received unexpected error:
        	            	Post "https://registration-service-toolchain-host-04125414.apps.ci-op-wsw002nh-887d4.devsandboxci.devcluster.openshift.com/api/v1/signup": EOF
        	Test:       	TestAfterMigration/run_migration_setup_with_new_operator_versions_for_compatibility
```

**Comment by mfrancisc** [comment]
> I noticed that it is failing with EOF

@rsoaresd thanks for investigating and pointing this out 🙏 

I'm looking into it, trying to reproduce locally , but having some other dev infrastructure issues atm 🤦

**Comment by rsoaresd** [comment]
@mfrancisc  I can try to reproduce locally too :) 

I am tracking the occurrences through this [search query](https://search.dptools.openshift.org/?search=EOF&maxAge=336h&context=1&type=build-log&name=.*codeready-toolchain.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)

**Comment by mfrancisc** [comment]
> I am tracking the occurrences through this [search query](https://search.dptools.openshift.org/?search=EOF&maxAge=336h&context=1&type=build-log&name=.*codeready-toolchain.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)

@rsoaresd nice! I wasn't aware of this search tool 😮 . Thanks for sharing! 

It seems that it happened only on my PR, so maybe related to my changes 🤔

**Review by alexeykazakov — APPROVED** [review]
Looks good. However there is a bit of inconsistency in how we organize templates in the host and member operators.
In the host we keep them in `/deploy/templates` while in the member there are in `/deploy`. Not sure if we want to do anything about that though.
But anyway we can address it in a separate PR if we want.

**Comment by mfrancisc** [comment]
> However there is a bit of inconsistency in how we organize templates in the host and member operators.
In the host we keep them in /deploy/templates while in the member there are in /deploy

@alexeykazakov thanks for the review and good point. I've updated member-operator to store the templates under `deploy/templates/` in https://github.com/codeready-toolchain/member-operator/pull/555/commits/7bb3fb995f140abf7434ef5203b085cb2dd1ca7b

**Review by alexeykazakov — APPROVED** [review]

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
