### PR TITLE
Add a service for proxy metrics in the registration-service deployment

### PR DESCRIPTION
**Pull request by ranakan19**
related to https://github.com/codeready-toolchain/registration-service/pull/352

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by mfrancisc — APPROVED** [review]

**Comment by MatousJobanek** [comment]
>  looks like an unrelated failure - checking if consistent

yeah, it apparently deployed the latest reg-service version but ran e2e tests without the latest commit merged yet. Just bad timing issue :-)

**Pull request merged**
