### PR TITLE
Add get/list bannedusers to reg-service SA

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by MatousJobanek** [comment]
This should be changed in registration-service first and then copied to host-operator - the source of the template is stored there. 
https://github.com/codeready-toolchain/registration-service/pull/94

**Comment by alexeykazakov** [comment]
@MatousJobanek we have already discussed it with @sbryzak. Shane is going to make the same changes in reg-service in https://github.com/codeready-toolchain/registration-service/pull/94
There are multiple other PRs which depend on this change so we decided to make this change in host-operator first.

**Comment by MatousJobanek** [comment]
Ok. It just have a small side effect while running `make generate` in `api` repo - the target copies the file from reg-service to host-operator so I need to revert that change every time.

**Comment by alexeykazakov** [comment]
> Ok. It just have a small side effect while running make generate in api repo - the target copies the file from reg-service to host-operator so I need to revert that change every time.

Oh.. I missed that. So, yeah, then updating the reg-service together with that change makes sense indeed.

**Pull request merged**
