### PR TITLE
Delete unused image stream manifest

### PR DESCRIPTION
**Pull request by alexeykazakov**
This ImageStream was previously used to update the operator in our crt-stage cluster. Now we use OLM for that.

### CODE REVIEW

**Comment by xcoulon** [comment]
> This ImageStream was previously used to update the operator in our crt-stage cluster. Now we use OLM for that.

This is an acknowledgement that we rely on OpenShift 4.x (unless someone wants to install OLM on OS3), so should we also remove code like https://github.com/codeready-toolchain/toolchain-e2e/blob/master/make/test.mk#L227-L233 too? 

@MatousJobanek WDYT?

**Comment by MatousJobanek** [comment]
@xcoulon please, do no remove anything related to OS3 (Minishift). For now, it's the only way I can run e2e tests in a reasonable time.

**Comment by xcoulon** [comment]
> @xcoulon please, do no remove anything related to OS3 (Minishift). For now, it's the only way I can run e2e tests in a reasonable time.

Ok, I understand. I thought you had some limitations with Minishift and it did not work for you.
I wouldn't remove anything without your review and approval anyways ;)

**Pull request merged**
