### PR TITLE
feat: allow communication from OLM namespaces

### PR DESCRIPTION
**Pull request by MatousJobanek**
to make WTO happy
https://coreos.slack.com/archives/CHK0J6HT6/p1623240761098300?thread_ts=1623165011.068300&cid=CHK0J6HT6

and added also another NetworkPolicy:

https://coreos.slack.com/archives/CHK0J6HT6/p1632143705135000?thread_ts=1632134003.130300&cid=CHK0J6HT6

paired with https://github.com/codeready-toolchain/toolchain-e2e/pull/316

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by xcoulon — CHANGES_REQUESTED** [review]
`deploy/templates/nstemplatetiers/team/*.yaml` were removed in https://github.com/codeready-toolchain/host-operator/pull/491, and we now have `deploy/templates/nstemplatetiers/baseextendedidling/*.yaml` introduced in https://github.com/codeready-toolchain/host-operator/pull/486

**Comment by MatousJobanek** [comment]
@xcoulon all conflicts fixed and PR updated

**Review by amisevsk — APPROVED** [review]
From the WTO perspective, looks good to me

**Review by sleshchenko — APPROVED** [review]
LGTM

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
