### PR TITLE
Add read access to additional Core GitOps APIs

### PR DESCRIPTION
**Pull request by jgwest**
Adds readonly access for appstudio users to gitopsdeploymentmanagedenvironments, gitopsdeploymentrepositorycredentials, gitopsdeploymentsyncrun APIs.

Corresponding test PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/693
Corresponding book PR: https://github.com/redhat-appstudio/book/pull/90

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
cc: @ranakan19

**Comment by alexeykazakov** [comment]
@jgwest there is currently another PR which we are going to merge soon: https://github.com/codeready-toolchain/host-operator/pull/775
That PR is based on https://github.com/redhat-appstudio/book/blob/main/ADR/0011-roles-and-permissions.md which is the source of truth for us now.
I suggest we do the following:
- @jgwest could you please create a PR against https://github.com/redhat-appstudio/book/blob/main/ADR/0011-roles-and-permissions.md to add these new CRDs? We need them added to all relevant roles.
- As soon as we have clarification around what role should have what permissions we will either ask @ranakan19 to update her PR to include those new CRDs if the PR is not merged yet. If it's merged then we will ask you to create a new PR too add these CRDs to the roles in our templates.

That will allow us to make sure:
- We keep the ADR doc up to date as our source of truth for role permissions.
- We don't risk loosing those permissions when trying to resolve conflicts with your and Kanika's PRs.
- We add the new CRDs with proper permissions to all relevant roles and not just to the admin.

**Review by alexeykazakov — CHANGES_REQUESTED** [review]
The PR looks good but see my comment above.

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
infra issue

/retest

**Review by ranakan19 — APPROVED** [review]
LGTM

**Review by MatousJobanek — APPROVED** [review]

**Comment by alexeykazakov** [comment]
Infra issue again :(

/retest

**Pull request merged**
