### PR TITLE
Add new tier that will not automatically deactivate users

### PR DESCRIPTION
**Pull request by rajivnathan**
Creates a new tier names `basic-no-deactivation` that is the same as the basic tier except without any deactivation timeout period `deactivationTimeoutDays`. Special user accounts that should not be automatically deactivated can be promoted to this new tier.

Also includes the following changes:
- Changes the basic tier's deactivation period to 1 day temporarily for real-world testing
- Adds the che.eclipse.org/openshift-username: ${USERNAME} annotation to the -code namespaces so that che will use the openshift username regardless of what the user inputs in the keycloak form. Background for context: eclipse/che#15323 (comment).
- Removes deactivationTimeoutDays for the advanced tier

e2e PR link: https://github.com/codeready-toolchain/toolchain-e2e/pull/207

Related issue: https://issues.redhat.com/browse/CRT-876

### CODE REVIEW

**Review by alexeykazakov — COMMENTED** [review]
Looks good! Just need to add/modify the e2e tests.

**Comment by rajivnathan** [comment]
test infra issue
/retest

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
