### PR TITLE
Update notification.html

### PR DESCRIPTION
**Pull request by Chr1st1anSears**
Updates text of welcome email per this issue: https://issues.redhat.com/browse/RHTAPBUGS-509

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
Could you please resolve the conflict?

**Comment by alexeykazakov** [comment]
Can you please update the test?

**Comment by Chr1st1anSears** [comment]
Hey @alexeykazakov, is there anything I should do regarding the test, or anything else, to help push this PR along? Or do we need to wait for input from other folks?

**Comment by alexeykazakov** [comment]
I fixed the tests for you.

**Comment by Chr1st1anSears** [comment]
> I fixed the tests for you.

Thank you--I didn't catch what needed to happen there

**Pull request merged**
