### PR TITLE
operator resource requests and limits

### PR DESCRIPTION
**Pull request by xcoulon**
Fixes https://issues.redhat.com/browse/CRT-786

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by MatousJobanek — COMMENTED** [review]
Please run:
`make generate-olm-files`
to propagate this change to CSV and other files

**Comment by xcoulon** [comment]
> Please run:
> `make generate-olm-files`
> to propagate this change to CSV and other files

thanks for the reminded @MatousJobanek! I just did it in https://github.com/codeready-toolchain/host-operator/pull/319/commits/458a00fe9bbbcb4f9f3f1eeb330b4006dd2a3d8f

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
