### PR TITLE
add security context to containers

### PR DESCRIPTION
**Pull request by ranakan19**
Add security context to containers for:
- run as non-root
- drop default capabilities
- limit privilege escalation

Since security context on container level applies only to that specific container, and overrides settings made at Pod level, security context has been added to individual containers.

### CODE REVIEW

**Review by mfrancisc — COMMENTED** [review]
Are you going to remove the manager_auth_proxy_patch as done for [member operator ](https://github.com/codeready-toolchain/member-operator/pull/465) ?

**Comment by ranakan19** [comment]
> Are you going to remove the manager_auth_proxy_patch as done for [member operator ](https://github.com/codeready-toolchain/member-operator/pull/465) ?

yep, was waiting for member operator e2e to be green, done now in [a1e0ebb](https://github.com/codeready-toolchain/host-operator/pull/837/commits/a1e0ebb7d17e3ea2462b9ec0d1690bbdf3f2f4a1)

**Review by mfrancisc — APPROVED** [review]
Looks good, nice job 👍

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
