### PR TITLE
Update admin spacerole role and rolebinding to indicate level

### PR DESCRIPTION
**Pull request by ralphbean**
When a cluster admin inspects a namespace, it would be helpful if the names of the roles and rolebindings consistently reflected their level.

Both the contributor and maintainer roles and rolebindings indicate their level in their names (contributor and maintainer respectively).

Here, do the same with admin for parity.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@mfrancisc please take a look.

**Comment by mfrancisc** [comment]
Looks good to me 👍  

I'm not sure why we avoided the keyword `admin` , maybe there was a reason behind this 🤷‍♂️ 

As @alexeykazakov pointed out, could you please create a PR also in toolchain-e2e with the same branch name. 
Basically updating the role name here : https://github.com/codeready-toolchain/toolchain-e2e/blob/82d14a8198f213081614ef91fe7579bc20eaa314/testsupport/tiers/checks.go#L1466

and rolebinding here: https://github.com/codeready-toolchain/toolchain-e2e/blob/82d14a8198f213081614ef91fe7579bc20eaa314/testsupport/tiers/checks.go#L1732-L1733

**Comment by alexeykazakov** [comment]
I don't remember any specific reason besides the fact that originally there was only one role. We didn't have "admin", "contributor", "maintainer". So it didn't have any name suffix for it. Then we introduced two more roles but didn't renamed the original one.

**Comment by mfrancisc** [comment]
> I don't remember any specific reason besides the fact that originally there was only one role.

Ok gotcha , that makes sense indeed! Thanks!

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
