### PR TITLE
Add Dev Environment CR to appstudio tier template

### PR DESCRIPTION
**Pull request by xcoulon**
requires https://github.com/codeready-toolchain/member-operator/pull/404 

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/653

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]

**Review by mfrancisc — APPROVED** [review]

**Review by alexeykazakov — APPROVED** [review]

**Comment by xcoulon** [comment]
thanks for merging the PR, @alexeykazakov!

**Pull request merged**
