### PR TITLE
remove webConsolePlugin from ToolchainClusterConfig (phase 1)

### PR DESCRIPTION
**Pull request by xcoulon**
phase 1: only remove the CRD

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
/retest

infra issue

**Comment by xcoulon** [comment]
/test e2e

(infra issue again)

**Review by rajivnathan — APPROVED** [review]

**Pull request merged**
