### PR TITLE
refactor: simplify the tier templates

### PR DESCRIPTION
**Pull request by xcoulon**
now using something like:
```
from: base
parameters:
- name: ...
  value: ...
```

fixes https://issues.redhat.com/browse/CRT-1264

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]
The change is simpler than I expected :+1:

**Comment by xcoulon** [comment]
> The change is simpler than I expected 👍

thanks for your feedback @MatousJobanek ;)

**Review by rajivnathan — APPROVED** [review]
This is better than I expected! Nicely done 🥇

**Comment by xcoulon** [comment]
> This is better than I expected! Nicely done 🥇

thanks for your feedback @rajivnathan !

**Pull request merged**
