### PR TITLE
Remove migration code and tests

### PR DESCRIPTION
**Pull request by sbryzak**
This PR removes all migration code, as all UserSignups have now been migrated.

Fixes https://issues.redhat.com/browse/CRT-1404

related e2e test PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/609

### CODE REVIEW

**Comment by MatousJobanek** [comment]
before we delete the migration code, we should probably also check if there is anything left in the RHOAM Sandbox, right? Or have you done that already?

**Comment by sbryzak** [comment]
@MatousJobanek have worked with Brian to ensure all his users are correctly migrated now.

**Review by xcoulon — APPROVED** [review]

**Pull request merged**
