### PR TITLE
move appstudio tiers to toolchain-e2e repo

### PR DESCRIPTION
**Pull request by MatousJobanek**
All appstudio tiers are managed by infra-deployments. To avoid any overrides and unexpected behavior in Konflux environment, we are moving all appstudio tiers (as they are) to toolchain-e2e repository. As part of the e2e test setup, we use ksctl to generate the NSTemplateTier and TierTemplate CRs to:
* verify that the generate command works as it's supposed to work
* all current e2e tests are working without any changes (there are many of them still relying on appstudio tiers)

There's gonna be a few follow-up PRs to clean it up, and make it more efficient. But there is no urgency for that.

There are also some unit tests using the dummy appstudio-env tiers in host-operator. This will be cleaned up in a separate PR.

paired PR https://github.com/codeready-toolchain/toolchain-e2e/pull/1017

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Comment by mfrancisc** [comment]
Actually I see now that they are also in prod : https://github.com/redhat-appstudio/infra-deployments/tree/main/components/sandbox/tiers/production , never mind!

**Review by mfrancisc — APPROVED** [review]

**Review by dperaza4dustbit — APPROVED** [review]
/lgtm

**Comment by dperaza4dustbit** [comment]
> I think we need to wait before merging this, since the tiers are only in stage infra-deployments if I'm not mistaken : [redhat-appstudio/infra-deployments#4162](https://github.com/redhat-appstudio/infra-deployments/pull/4162)

They are in prod as well @mfrancisc

**Review by rajivnathan — APPROVED** [review]

**Pull request merged**
