### PR TITLE
reorg NSTemplateTier files

### PR DESCRIPTION
**Pull request by xcoulon**
- move all namespace template files to `deploy/nstemplatetiers`
  so they are with the other manifests, under `deploy`
- move and rename the generate go file to `template_contents`

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by xcoulon** [comment]
> @xcoulon Don't forget to change the import in the template_contents_test.go file ;-)
> https://github.com/codeready-toolchain/host-operator/blob/f719553d83a1fa1da2e48dbbe1fdb2d7e198ab17/pkg/templates/template_contents_test.go#L7

this is what happens when I'm so confident about the change that I don't even run the tests locally, and of course, they fail on OpenShift CI 😜
Let me fix that now!

**Comment by MatousJobanek** [comment]
not sure why, but the test is failing locally:
```
--- FAIL: TestTemplates (0.00s)
    --- FAIL: TestTemplates/basic-code (0.00s)
        require.go:794: 
            	Error Trace:	template_contents_test.go:24
            	Error:      	Received unexpected error:
            	            	Asset basic-code.yml not found
            	Test:       	TestTemplates/basic-code
FAIL
FAIL	github.com/codeready-toolchain/host-operator/pkg/templates	0.009s
```

**Comment by xcoulon** [comment]
> not sure why, but the test is failing locally:
> 
> ```
> --- FAIL: TestTemplates (0.00s)
>     --- FAIL: TestTemplates/basic-code (0.00s)
>         require.go:794: 
>             	Error Trace:	template_contents_test.go:24
>             	Error:      	Received unexpected error:
>             	            	Asset basic-code.yml not found
>             	Test:       	TestTemplates/basic-code
> FAIL
> FAIL	github.com/codeready-toolchain/host-operator/pkg/templates	0.009s
> ```

Yes, I've seen this as well. It's because `go-bindata` generates the assets with a prefix based on the path/folder where the source files were located, so I also need to change that!

**Comment by xcoulon** [comment]
> > not sure why, but the test is failing locally:
> > ```
> > --- FAIL: TestTemplates (0.00s)
> >     --- FAIL: TestTemplates/basic-code (0.00s)
> >         require.go:794: 
> >             	Error Trace:	template_contents_test.go:24
> >             	Error:      	Received unexpected error:
> >             	            	Asset basic-code.yml not found
> >             	Test:       	TestTemplates/basic-code
> > FAIL
> > FAIL	github.com/codeready-toolchain/host-operator/pkg/templates	0.009s
> > ```
> 
> Yes, I've seen this as well. It's because `go-bindata` generates the assets with a prefix based on the path/folder where the source files were located, so I also need to change that!

fixed in cbd7505

**Pull request merged**
