### PR TITLE
Small fix to prevent silent failure when loading tier files

### PR DESCRIPTION
**Pull request by rajivnathan**
I ran into a situation where my e2e tests were failing with the following error:
```
    host.go:439: NSTemplateTier 'basic' in namespace 'sandbox-host' is not matching the expected criteria
    host.go:423: waiting until NSTemplateTier 'basic' is created or updated in namespace 'sandbox-host'...
    host.go:439: NSTemplateTier 'basic' in namespace 'sandbox-host' is not matching the expected criteria
    host.go:423: waiting until NSTemplateTier 'basic' is created or updated in namespace 'sandbox-host'...
    host.go:439: NSTemplateTier 'basic' in namespace 'sandbox-host' is not matching the expected criteria
    tier_setup.go:98:
        	Error Trace:	tier_setup.go:98
        	            				user_setup.go:113
        	            				user_setup.go:37
        	            				e2e_test.go:63
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestE2EFlow
```

The host operator logs didn't show anything wrong with setup of the tiers:
```
{"level":"info","ts":1614105529.6045566,"logger":"cmd","msg":"Creating/updating the NSTemplateTier resources"}
{"level":"info","ts":1614105529.604777,"logger":"cmd","msg":"Created/updated the NSTemplateTier resources"}
```

This was the case even with the same code as master which was clearly working fine in the CI tests. It took a bit of digging but it turned out that the host operator loadTemplatesByTiers func was failing silently because I had a `.DS_Store` file that must have been created by opening the directory using Finder at some point.

The unit tests were failing with:
```
        --- FAIL: TestLoadTemplatesByTiers/ok/with_prod_assets (0.00s)
            nstemplatetier_generator_whitebox_test.go:42:
                	Error Trace:	nstemplatetier_generator_whitebox_test.go:42
                	Error:      	"map[]" should have 5 item(s), but has 0
                	Test:       	TestLoadTemplatesByTiers/ok/with_prod_asset
```

With this slight change the unit tests will fail with:
```
        --- FAIL: TestLoadTemplatesByTiers/ok/with_prod_assets (0.00s)
            nstemplatetier_generator_whitebox_test.go:39:
                	Error Trace:	nstemplatetier_generator_whitebox_test.go:39
                	Error:      	Received unexpected error:
                	            	unable to load templates: invalid name format for file '.DS_Store'
                	Test:       	TestLoadTemplatesByTiers/ok/with_prod_assets
```

And the host operator will be clearly failing with `CrashLoopBackOff` and logs showing:
```
{"level":"info","ts":1614125951.5739002,"logger":"cmd","msg":"Creating/updating the NSTemplateTier resources"}
{"level":"error","ts":1614125951.574131,"logger":"cmd","msg":"","error":"unable to create TierTemplates: unable to load templates: invalid name format for file '.DS_Store'","errorVerbose":"unable to load templates: invalid name format for file '.DS_Store'\nunable to create TierTemplates\ngithub.com/codeready-toolchain/host-operator/pkg/templates/nstemplatetiers.CreateOrUpdateResources\n\t/Users/rajiv/go/src/github.com/codeready-toolchain/host-operator/pkg/templates/nstemplatetiers/nstemplatetier_generator.go:36\nmain.main.func1\n\t/Users/rajiv/go/src/github.com/codeready-toolchain/host-operator/cmd/manager/main.go:188\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/rajiv/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main.func1\n\t/Users/rajiv/go/src/github.com/codeready-toolchain/host-operator/cmd/manager/main.go:189"}
```

### CODE REVIEW

**Review by alexeykazakov — COMMENTED** [review]
Good catch. But it means we don't have a unit test to cover that error, right? Can we add some?

**Comment by rajivnathan** [comment]
The unit tests did actually catch the problem.

```
        --- FAIL: TestLoadTemplatesByTiers/ok/with_prod_assets (0.00s)
            nstemplatetier_generator_whitebox_test.go:42:
                	Error Trace:	nstemplatetier_generator_whitebox_test.go:42
                	Error:      	"map[]" should have 5 item(s), but has 0
                	Test:       	TestLoadTemplatesByTiers/ok/with_prod_asset
```

But you're right we could add a test specifically for invalid name format.

**Review by alexeykazakov — APPROVED** [review]
Thanks for the tests!

**Review by MatousJobanek — APPROVED** [review]
Nice catch :+1:

**Pull request merged**
