### PR TITLE
Add support for mutil-architecture

### PR DESCRIPTION
**Pull request by krishvoor**
Fixes - https://issues.redhat.com/browse/CRT-1041

This PR allows to identify underlying and build
corresponding binaries as required

Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Sorry, closed it accidentally. Re-opening now :)

**Review by alexeykazakov — APPROVED** [review]
Thanks for fixing it!

**Comment by alexeykazakov** [comment]
We will need to change it in all our repos.

**Comment by krishvoor** [comment]
Here are the PR's for the following repositories -

For toolchain-e2e https://github.com/codeready-toolchain/toolchain-e2e/pull/282
For host-operator https://github.com/codeready-toolchain/host-operator/pull/407
For member-operator https://github.com/codeready-toolchain/member-operator/pull/242
For registration-service https://github.com/codeready-toolchain/registration-service/pull/180

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
