### PR TITLE
config: output logs in JSON format

### PR DESCRIPTION
**Pull request by xcoulon**
needed so the Fluentd logforwarder can parse the logs

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by MatousJobanek — COMMENTED** [review]
Is there any documentation/guide/explanation for this config?
What the logs will look like?

**Comment by xcoulon** [comment]
> Is there any documentation/guide/explanation for this config? What the logs will look like?

with logs in JSON format, Loki can parse the message and extract the date, level and message. 
The logs will look like this:
```
{"level":"info","ts":1632927404.1876383,"logger":"controller-runtime.manager.controller.toolchainconfig","msg":"All objects in registration service template have been created and are up-to-date","reconciler group":"toolchain.dev.openshift.com","reconciler kind":"ToolchainConfig","name":"config","namespace":"toolchain-host-operator"}
```
I understand it's less human friendly, but that's the combination of format/config that I found to work so we can get logs in Loki in a meaningful way :/

**Comment by xcoulon** [comment]
> > Is there any documentation/guide/explanation for this config? What the logs will look like?
> 
> with logs in JSON format, Loki can parse the message and extract the date, level and message. The logs will look like this:
> 
> ```
> {"level":"info","ts":1632927404.1876383,"logger":"controller-runtime.manager.controller.toolchainconfig","msg":"All objects in registration service template have been created and are up-to-date","reconciler group":"toolchain.dev.openshift.com","reconciler kind":"ToolchainConfig","name":"config","namespace":"toolchain-host-operator"}
> ```
> 
> I understand it's less human friendly, but that's the combination of format/config that I found to work so we can get logs in Loki in a meaningful way :/

that being said, we could probably add a config parameter to switch the logger output format from "text" to "JSON" when deploying on production, if it can help.

**Comment by MatousJobanek** [comment]
ok, so the human-friendly time format will be replaced by the timestamp, right? What a pity - I like the way it is logged now. Couldn't we use a different `TimeEncoder` for that? 
As for the rest - yeah, I understand that it's needed to put it into the JSON format to make it parsable.

**Comment by xcoulon** [comment]
> ok, so the human-friendly time format will be replaced by the timestamp, right? What a pity - I like the way it is logged now. Couldn't we use a different `TimeEncoder` for that? As for the rest - yeah, I understand that it's needed to put it into the JSON format to make it parsable.

ah, I see your point with regards to the timestamp. Let me see about that

**Comment by xcoulon** [comment]
> ok, so the human-friendly time format will be replaced by the timestamp, right? What a pity - I like the way it is logged now. Couldn't we use a different `TimeEncoder` for that? As for the rest - yeah, I understand that it's needed to put it into the JSON format to make it parsable.

With d238124, here's what the logs look like:
```
...
{"level":"info","ts":"2021-10-01T07:28:17.855Z","logger":"setup","msg":"Created/updated the ToolchainStatus resource"}
{"level":"info","ts":"2021-10-01T07:28:17.855Z","logger":"setup","msg":"Creating/updating the NSTemplateTier resources"}
...
```

**Comment by MatousJobanek** [comment]
@xcoulon awesome - this is much better :star_struck:  Thanks a lot for taking a look at it. 
Do you know by any chance what the error is printed out like? I mean the whole stacktrace - if it's a single line or multiple lines as we see now.

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
