### PR TITLE
Remove the CapacityThresholds from ToolchainConfig

### PR DESCRIPTION
**Pull request by metlos**
This updates the code and tests to not use CapacityThresholds from ToolchainConfig for anything because this field has been removed from the api.

See https://issues.redhat.com/browse/KUBESAW-36.

Associated PRs:
    - toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/379
    - toolchain-e2e: https://github.com/codeready-toolchain/toolchain-e2e/pull/935
    - api: https://github.com/codeready-toolchain/api/pull/411

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by MatousJobanek — COMMENTED** [review]
looks good, but include the regenerated CRD please

**Comment by rsoaresd** [comment]
[Latest run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_host-operator/1000/pull-ci-codeready-toolchain-host-operator-master-e2e/1772972219522093056#1:build-log.txt%3A19455) failed with:

```
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestE2EFlow/verify_Space_is_not_deleted_if_namespace_is_not_deleted
push_pin
        	Messages:   	The proper cleanup of the UserSignup 'laracroft' and related resources wasn't finished within the given timeout
        	            	the UserSignup 'laracroft' has been cleaned properly 
        	            	the MasterUserRecord 'laracroft' has been cleaned properly 
        	            	the Space 'laracroft' is still present in the cluster
```

I saw that also happened in the past 13 days in [registration-service job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_registration-service/413/pull-ci-codeready-toolchain-registration-service-master-e2e/1768208876684972032#1:build-log.txt%3A17993). Very likely is a flaky test. I will investigate it.

**Review by MatousJobanek — APPROVED** [review]

**Review by rajivnathan — APPROVED** [review]

**Comment by rsoaresd** [comment]
Hello, @metlos!

The last two runs are hitting:

```
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: [controlPlane.platform.aws: Internal error: error listing instance types: fetching instance types: UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:iam::767398085593:user/sandboxOpenShiftCI is not authorized to perform: ec2:DescribeInstanceTypes with an explicit deny in a service control policy
level=error msg=	status code: 403, request id: a6397df6-1005-4af8-8363-71e8444946da, compute[0].platform.aws: Internal error: error listing instance types: fetching instance types: UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:iam::7673980[85](https://prow.ci.openshift.org/spyglass/lens/buildlog/iframe?req=%7B%22artifacts%22%3A%5B%22build-log.txt%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gs%2Ftest-platform-results%2Fpr-logs%2Fpull%2Fcodeready-toolchain_host-operator%2F1000%2Fpull-ci-codeready-toolchain-host-operator-master-e2e%2F1777609530872434688%22%7D&topURL=https%3A//prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_host-operator/1000/pull-ci-codeready-toolchain-host-operator-master-e2e/1777609530872434688&lensIndex=1#build-log.txt:85)593:user/sandboxOpenShiftCI is not authorized to perform: ec2:DescribeInstanceTypes with an explicit deny in a service control policy
level=error msg=	status code: 403, request id: d410e482-1dfe-448f-8b6a-64cc34f854ee]
Create manifests exit code: 3
```

**Review by fbm3307 — APPROVED** [review]

**Pull request merged**
