### PR TITLE
Move to the new name of the tekton sa

### PR DESCRIPTION
**Pull request by sbose78**
The old service account has been phased out.

Impacts 
https://issues.redhat.com/browse/RHTAPBUGS-338

e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/741

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Review by adambkaplan — APPROVED** [review]
/lgtm

Looks correct.

**Review by alexeykazakov — APPROVED** [review]
You also need to create a paired e2e PR to cover this change.
Please create a PR with the same branch name as this one (so our CI can pair the PRs) and update the SA name here: https://github.com/codeready-toolchain/toolchain-e2e/blob/2b54e59598f40d93c94c2a457d5ebe96cca4f962/testsupport/tiers/checks.go#L1487

**Comment by alexeykazakov** [comment]
@sbose78 you didn't pair the PRs correctly. It has to be the same branch name. This PR is using `sbose78:appstudio-pipeline` While https://github.com/codeready-toolchain/toolchain-e2e/pull/737 is using `sbose78:tekton-sa`

**Comment by sbose78** [comment]
All tests green ✅

**Comment by Roming22** [comment]
@alexeykazakov Is there anything holding up the merge of this PR?

**Comment by alexeykazakov** [comment]
Will get it merged as soon as https://github.com/codeready-toolchain/toolchain-e2e/pull/741 is ready to be merged.

**Pull request merged**
