### PR TITLE
Use the base tier as the default for new approvals

### PR DESCRIPTION
**Pull request by rajivnathan**
Related issue: https://issues.redhat.com/browse/CRT-985

Updates the automatic approval to use the base tier by default

e2e-tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/277

### CODE REVIEW

**Review by alexeykazakov — COMMENTED** [review]
Looks good. Just waiting for the e2e tests :)

**Comment by rajivnathan** [comment]
@alexeykazakov e2e tests added

**Review by alexeykazakov — APPROVED** [review]

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
