### PR TITLE
adding fields for notification service

### PR DESCRIPTION
**Pull request by tinakurian**
result of: https://github.com/codeready-toolchain/api/pull/127

Jira Task: https://issues.redhat.com/browse/CRT-518

### CODE REVIEW

**Comment by tinakurian** [comment]
> There should be more files to be changed. Are you sure you ran `make generate` from api repo?

hm.. i just ran it again (make clean, make generate) and the only other change i see is in member-operator for pkg/cluster/kubefedcluster_assets.go - which is not related to this change..

**Comment by alexeykazakov** [comment]
do you see any errors? what operator-sdk version are you using?

**Comment by tinakurian** [comment]
> do you see any errors? what operator-sdk version are you using?

@alexeykazakov upgraded the operator-sdk version and regenerated - does this look better? i don't see any errors now when running make generate

**Pull request merged**
