### PR TITLE
KSPACE-20: Drop the distinction between host & member ToolchainClusters

### PR DESCRIPTION
**Pull request by fbm3307**
This is related to Drop the distinction between host & member ToolchainClusters
Related PRs:
ToolchainCommon- https://github.com/codeready-toolchain/toolchain-common/pull/359
Member-Operator - https://github.com/codeready-toolchain/member-operator/pull/531
Registration-Service - https://github.com/codeready-toolchain/registration-service/pull/402
Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/893
Sandbox-sre - https://github.com/codeready-toolchain/sandbox-sre/pull/1524

### CODE REVIEW

**Review by metlos — APPROVED** [review]

**Comment by fbm3307** [comment]
closing this as i messed up the rebase .

**Pull request closed without merging**
